name: Check Overleaf Sync

on:
  pull_request:
    branches:
      - overleaf

jobs:
  check-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if Overleaf is ahead
        env:
          OVERLEAF_PASSWORD: ${{ secrets.OVERLEAF_PASSWORD }}
        run: |
          git remote add overleaf https://git:${OVERLEAF_PASSWORD}@git.overleaf.com/68c075c10ebc8872716b6f42
          git fetch overleaf master
          git fetch origin overleaf

          BEHIND=$(git rev-list origin/overleaf..overleaf/master --count)

          if [ "$BEHIND" -gt 0 ]; then
            echo "No se puede! Hay cambios en Overleaf que hay que traerse"
            exit 1
          fi

          echo "Parece que se puede mergear."
